const LANGUAGE_CREATE='LANGUAGE_CREATE';
const LANGUAGE_FINISHED='LANGUAGE_FINISHED';
const LANGUAGE_CHANGE='LANGUAGE_CHANGE';
const FETCH_DATA_START='FETCH_DATA_START';
const FETCH_DATA_SUCCESS='FETCH_DATA_SUCCESS';
const FETCH_DATA_FAILURE='FETCH_DATA_FAILURE';
const SETTINGS_CHANGE_VISIBLE='SETTINGS_CHANGE_VISIBLE';
const SETTINGS_CHANGE='SETTINGS_CHANGE';
const FILTER_CHANGE_VISIBLE='FILTER_CHANGE_VISIBLE';
const EMPLOYEE_CHANGE_DATA='EMPLOYEE_CHANGE_DATA';



export {
    LANGUAGE_CREATE,
    LANGUAGE_FINISHED,
    LANGUAGE_CHANGE,
    FETCH_DATA_START,
    FETCH_DATA_SUCCESS,
    FETCH_DATA_FAILURE,
    SETTINGS_CHANGE_VISIBLE,
    SETTINGS_CHANGE,
    FILTER_CHANGE_VISIBLE,
    EMPLOYEE_CHANGE_DATA,
}