const LANGUAGE_CREATE='LANGUAGE_CREATE';
const LANGUAGE_FINISHED='LANGUAGE_FINISHED';
const LANGUAGE_CHANGE='LANGUAGE_CHANGE';
const FETCH_DATA_START='FETCH_DATA_START';
const FETCH_DATA_SUCCESS='FETCH_DATA_SUCCESS';
const FETCH_DATA_FAILURE='FETCH_DATA_FAILURE';


export {
    LANGUAGE_CREATE,LANGUAGE_FINISHED,LANGUAGE_CHANGE,FETCH_DATA_START,FETCH_DATA_SUCCESS,FETCH_DATA_FAILURE,
}