const LANGUAGE_CHANGE='LANGUAGE_CHANGE';
const FETCH_DATA_START='FETCH_DATA_START';
const FETCH_DATA_SUCCESS='FETCH_DATA_SUCCESS';
const FETCH_DATA_FAILURE='FETCH_DATA_FAILURE';
const SETTINGS_CHANGE_VISIBLE='SETTINGS_CHANGE_VISIBLE';
const SETTINGS_SET='SETTINGS_SET';
const FILTER_CHANGE_VISIBLE='FILTER_CHANGE_VISIBLE';
const EMPLOYEE_CHANGE_DATA='EMPLOYEE_CHANGE_DATA';
const EMPLOYEE_CHANGE_COMPANY='EMPLOYEE_CHANGE_COMPANY';
const EMPLOYEE_CHANGE_SORT="EMPLOYEE_CHANGE_SORT";
const SEARCH_SET='SEARCH_SET';
const EMPLOYEE_CHANGE_TOOLTIP="EMPLOYEE_CHANGE_TOOLTIP";
const EMPLOYEE_CHANGE_ACTIVE_PAGE="EMPLOYEE_CHANGE_ACTIVE_PAGE";
const EMPLOYEE_CHANGE_ITEM_PAGE="EMPLOYEE_CHANGE_ITEM_PAGE";




export {
    LANGUAGE_CHANGE,
    FETCH_DATA_START,
    FETCH_DATA_SUCCESS,
    FETCH_DATA_FAILURE,
    SETTINGS_CHANGE_VISIBLE,
    SETTINGS_SET,
    FILTER_CHANGE_VISIBLE,
    EMPLOYEE_CHANGE_DATA,
    EMPLOYEE_CHANGE_COMPANY,
    EMPLOYEE_CHANGE_SORT,
    EMPLOYEE_CHANGE_TOOLTIP,
    EMPLOYEE_CHANGE_ACTIVE_PAGE,
    EMPLOYEE_CHANGE_ITEM_PAGE,
    SEARCH_SET,

}